-- phpMyAdmin SQL Dump
-- version 4.2.7.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Nov 11, 2014 at 02:04 PM
-- Server version: 5.6.20
-- PHP Version: 5.5.15

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `520_demo_st`
--

-- --------------------------------------------------------

--
-- Table structure for table `bldgdir_company`
--

CREATE TABLE IF NOT EXISTS `bldgdir_company` (
`company_id` int(4) unsigned NOT NULL,
  `sort_number` int(4) unsigned NOT NULL,
  `name` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `small_logo_path` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '200x200',
  `large_logo_path` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '320x310',
  `lift_bank` varchar(5) COLLATE utf8_unicode_ci NOT NULL,
  `phone` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `levels` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `website` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `information` text COLLATE utf8_unicode_ci,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `disabled` int(1) unsigned NOT NULL DEFAULT '0'
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=179 ;

--
-- Dumping data for table `bldgdir_company`
--

INSERT INTO `bldgdir_company` (`company_id`, `sort_number`, `name`, `small_logo_path`, `large_logo_path`, `lift_bank`, `phone`, `email`, `levels`, `website`, `information`, `update_time`, `disabled`) VALUES
(100, 1000, 'Maddocks', 'upload/100/slogo.png', 'upload/100/llogo.png', 'R', '03 9258 3555', 'info@maddocks.com.au', '6 - 11', 'www.maddocks.com.au', 'Maddocks provides premium legal services to corporations, businesses and governments throughout Australia and internationally. We advise across a diverse range of industry sectors, delivering advice from our Sydney, Melbourne and Canberra offices.\nWe’re committed to our clients. In fact, our brand and business reputation is built on them. Our customised service is based on a deep understanding of our clients’ legal requirements in the context of their business objectives. We’re highly regarded for exceptional, practical legal services that add value to our clients’ businesses.', '2014-11-11 11:06:16', 0),
(101, 1010, 'BDO', 'upload/101/slogo.png', 'upload/101/llogo.png', 'R', '03 9603 1700', 'Reception.Melbourne@bdo.com.au', '12 - 14', 'www.bdo.com.au', 'BDO is one of the largest full service accounting and advisory networks in Australia and globally. We excel at creating strong relationships with clients who are seeking a combination of technical excellence with a specialised range of services and a desire for outstanding client relationships. Our ability to create and maintain outstanding relationships is based on our understanding that each of our clients is distinctively different, and it is their unique needs that drive our distinctively different approach. Our clients tell us it is the way we listen to them, work with them, and how we see them, that makes our approach distinctively different. ', '2014-11-11 11:06:23', 0),
(102, 1020, 'ESSSuper', 'upload/102/slogo.png', 'upload/102/llogo.png', 'L', '1300 655 476', 'info@esssuper.com.au', '14 - 16', 'www.esssuper.com.au', 'ESSSuper is the superannuation fund for eligible Victorian state Government employees and emergency services workers. With 150,000 members and over $15 billion in funds under management ESSSuper provides a range of superannuation and retirement products and services for every life stage. For further information call our Member Service Centre on 1300 655 476 or visit our website, www.esssuper.com.au.', '2014-11-11 11:06:29', 0),
(103, 1030, 'Protiviti', 'upload/103/slogo.png', 'upload/103/llogo.png', 'L', '03 9948 1200', 'Melbourne@protiviti.com.au', '17', 'www.protiviti.com.au ', 'Protiviti is a global business consulting and internal audit firm composed of leading experts specialising in risk, advisory and transaction services. Over 3,700 professionals provide consulting and internal audit solutions to over 35 percent of both the FORTUNE® 500 and Global 1000 corporations in:\r\n•	Business Performance Improvement\r\n•	IT Consulting, Risk and Compliance\r\n•	Internal Audit and Financial Advisory\r\nOur highly trained, results-oriented professionals provide a unique perspective on a wide range of issues for clients in the Americas, Asia-Pacific, Europe and the Middle East.', '2014-10-17 03:34:56', 0),
(104, 1040, 'DLA Piper', 'upload/104/slogo.png', 'upload/104/llogo.png', 'L', '03 9274 5000', '', '17 - 22', 'www.dlapiper.com', 'DLA Piper is a global law firm with 4,200 lawyers in the Americas, Asia Pacific, Europe and the Middle East, positioning us to help companies with their legal needs around the world. \r\nWe strive to be the leading global business law firm by delivering quality and value to our clients. \r\n \r\nIn Australia we provide clients with an extensive breadth and depth of service across five capital cities nationally. We have approximately 600 legal staff based in Sydney, Melbourne, Brisbane, Perth and Canberra. \r\n \r\nAs trusted legal advisors to approximately a third of the ASX 100 companies or their subsidiaries and all levels of government, we take great pride in our reputation as a firm that is friendly, accessible and easy to do business with. It is our priority to spend time with our clients, getting to know them so that we can understand their businesses and provide strategic and innovative legal solutions that are practical and commercially focused. \r\n', '2014-11-11 11:06:36', 0),
(105, 1050, 'Etihad Airways', 'upload/105/slogo.png', 'upload/105/llogo.png', 'F', '03 8638 5100', 'austkt@etihad.ae', '25', 'www.etihad.com', 'Etihad Airways began operations in 2003, and in 2013 carried 11.5 million passengers. From its Abu Dhabi base Etihad Airways flies to 108 existing or announced passenger and cargo destinations in the Middle East, Africa, Europe, Asia, Australia and the Americas. The airline has a fleet of 104 Airbus and Boeing aircraft, and more than 200 aircraft on firm order, including 71 Boeing 787s, 25 Boeing 777-X, 62 Airbus A350s and 10 Airbus A380s. Etihad Airways holds equity investments in airberlin, Air Seychelles, Virgin Australia, Aer Lingus, Air Serbia and Jet Airways, and is in the process of formalising equity investments in Alitalia and Swiss-based Etihad Regional*. For more information, please visit: www.etihad.com.\n\n*Operated by Darwin Airline', '2014-11-11 11:12:40', 0),
(106, 1060, 'Savills', 'upload/106/slogo.png', 'upload/106/llogo.png', 'F', '03 8686 8000', 'melbourne@savills.com.au', '25', 'savills.com.au ', 'Savills is a leading global property service provider listed on the London Stock Exchange. Trusted since 1855, we have deep experience across the Asia Pacific, with over 50 offices, and in Australia we have over 800 staff focused on meeting all your property needs.', '2014-10-17 03:34:56', 0),
(107, 1070, 'Super Investment Management', '', '', 'F', '03 9609 9700', '', '26', '', 'Super Investment Management (SIM) is a wholly owned subsidiary company of REST Superannuation, an Australian industry superannuation fund. \r\nSIM is the in-house specialist investment manager for REST Superannuation, specialising in Fixed Interest, Infrastructure, Property investments, Australian Equities and Direct Debt. \r\n', '2014-11-11 12:25:15', 0),
(108, 1080, 'REST Industry Super', 'upload/108/slogo.png', 'upload/108/llogo.png', 'F', '03 9609 9888', '', '26', 'www.rest.com.au', 'The Retail Employees Superannuation Trust (REST) was established in 1988.  REST is amongst the largest industry superannuation funds by membership and is open to all Australians. REST has over 2 million members and over $30 billion of funds under management.', '2014-10-17 03:34:56', 0),
(109, 1090, 'legalsuper', 'upload/109/slogo.png', 'upload/109/llogo.png', 'F', '03 9602 0100', 'mail@legalsuper.com.au', '26', 'www.legalsuper.com.au', 'legalsuper is the $2.3 billion-plus industry superannuation fund dedicated to delivering a better retirement for members of the legal community.\nEstablished in March 1989, the fund known today as legalsuper was formed over twenty-five years ago by the establishment of the Legal Industry Superannuation Scheme (‘LISS’).\nLISS was established by the Law Institute of Victoria (‘LIV’) in March 1989 to provide a superannuation fund for members of the Victorian legal profession. The LIV also operated a superannuation fund for its employees known as the Law Institute of Victoria Staff Superannuation Plan. Another fund was operated for Victorian self-employed legal practitioners, known as the Victorian Solicitors.', '2014-11-11 11:10:10', 0),
(110, 1185, 'Madgwicks Lawyers (Reception Floor 33)', 'upload/110/slogo.png', 'upload/110/llogo.png', 'F', '03 9242 4744', 'madgwicks@madgwicks.com.au', '33 & 27', 'www.madgwicks.com.au', 'Madgwicks is a full service business law firm.  Our main practice areas are corporate and commercial law, commercial property, commercial litigation, insolvency and reconstruction and workplace relations. We pride ourselves on the development and management of long-term relationships with our clients.\r\n\r\nThe firm’s strategic imperatives are guided by a small set of core principles. These principles are:\r\n•             Outcome Focused\r\n•             Connected\r\n•             Easy to Work With\r\n\r\nThese principles have been identified by the firm as being an intrinsic part of its identity and culture. Madgwicks views these principles as fundamental to the existing and continuing success of the firm. They also encapsulate what the firm understands and espouses to be its difference to other firms. This understanding comes from feedback from a wide range of clients and referrers together with internal analysis as a part of the firm’s strategic planning process. Clients can expect and hold the firm’s service providers to be accountable to each of these principles.\r\n\r\nThe firm is part of Meritas, one of the world’s largest international affiliations of independent law firms. This alliance provides Madgwicks’ clients with access to 230 lawyers in Australia and New Zealand and 6,900 lawyers in more than 80 countries around the world.\r\n', '2014-11-11 12:59:51', 0),
(111, 1110, 'Evado eClinical', 'upload/111/slogo.png', 'upload/111/llogo.png', 'F', '03 9600 3616', 'info@evado.com', '27', 'www.evado.com', 'Evado is an internationally recognised solution provider of  cloud based clinical trials and patient registry software.   Our clients include  universities, international pharma  companies, emerging biotech start ups, and medical device manufacturers.  Evado solution’s  capture data in accordance with FDA requirements both domestically and internationally.  Evado’s UniFORM technology mobile enables our applications so that data can be collected and viewed in a mobile environment on any device, eg., a phone or iPad or Android for clinical trials and registry trials and studies.  For more information, please visit us on facebook,  evado e-clinical solutions, or our website www.evado.com.', '2014-10-17 03:34:56', 0),
(112, 1120, 'Aitken Partners', 'upload/112/slogo.png', 'upload/112/llogo.png', 'F', '03 8600 6000', 'info@aitken.com.au ', '28', 'www.aitken.com.au', 'Aitken Partners is a premium level Melbourne-based law firm offering a range of legal services to business and private clients. We have nine partners and 25 other professional staff, many of whom are Accredited Specialists in their fields (including Commercial Litigation, Tax Law, Workplace Law, Family Law, Wills & Estates and Property Law) and registered migration agents. \r\nAitken Partners has prospered for more than nine decades through a combination of professional, personal service based on sound advice and a careful focus on our clients'' needs. Our overriding philosophy is to build long-term sustainable relationships, and we do this by concentrating on the things that count to our clients. \r\nWe have a broad range of experience across most facets of the law and serve a range of business and private clients, both locally, interstate and overseas. Our holistic approach means we work to understand our clients, their needs and their industries.\r\nWe are on the Federal Government''s legal panels for Commercial Law (including Property Law) and Litigation & Dispute Resolution, placing us alongside some of the biggest law firms in Australia and one of only two Victoria-only firms. We believe being placed on the panel is a testament to the excellent legal services we provide.\r\nWe have an integrated IT strategy that is fully compliant with our Business Continuity Plan, using the latest software from Microsoft and other vendors for some of the more job specific tasks required by a law firm.\r\n', '2014-11-11 10:47:58', 0),
(113, 1130, 'Plenary Group', 'upload/113/slogo.png', 'upload/113/llogo.png', 'F', '03 8888 7700', 'mary.kotsiski@plenarygroup.com.au', '29', 'www.plenarygroup.com', 'Plenary Group is a leading international infrastructure business with large, experienced management teams located in the Americas and the Asia Pacific region.\r\nAs an independent long-term investor, sponsor and operator of public infrastructure, Plenary Group adopts a holistic approach to delivering its projects.\r\nThis is reflected in our hands on approach – embracing finance, planning, design and construction, complementary commercial development, and asset management and operations.\r\n•	Public-Private Partnerships (PPP or P3) infrastructure experts\r\n•	projects valued at some $14 billion\r\n•	established track record in Asia Pacific and the Americas\r\n•	local teams and expertise drawing on global perspectives\r\n•	hands-on management, from project design through to long-term operation\r\n•	innovative and sustainable solutions for public infrastructure\r\n•	secure, value-for-money, bankable results.\r\nOur reputation is built on having delivered diverse and challenging privately financed public infrastructure projects. The Plenary team prides itself on innovation, finding new ways to overcome traditional obstacles.\r\nWe strive to create community assets that offer value for money for governments and taxpayers. Characteristically, we actively manage the performance of our projects with an uncompromising focus on whole-of-lifecycle performance.\r\nGovernments and public sector agencies look to Plenary to be a trusted and authoritative voice as to the best manner in which to undertake public infrastructure that meets the genuine needs and aspirations of a community.\r\n', '2014-10-17 03:34:56', 0),
(114, 1140, 'Australian Securities', 'upload/114/slogo.png', 'upload/114/llogo.png', 'F', '03 9607 8111', 'mail@asltd.com.au', '29', 'www.australiansecurities.com.au', 'The responsible entity for Private Funds, since 1925. ASL offers private investors an investment in Australian Securities Income Fund and Australian Securities Property Fund.  Australian Securities also finances private, business, not for profit and SMF clients.', '2014-10-17 03:34:56', 0),
(115, 1150, 'Nicholas O''Donohue & Co Lawyers', 'upload/115/slogo.png', 'upload/115/llogo.png', 'F', '03 9607 8100', 'mail@nodco.com.au', '29', 'www.nodco.com.au', 'A boutique law firm founded in 1925. ‘Where Law Works’ is the firms philosophy. Our lawyers protect, guide and assist clients in every transaction to achieve a successful outcome\r\nThe firm represents four generations of clients that include leaders in industry, foundations small business and private clients. Areas of practice include Commercial, Financial Services, Guardianship & Administration, Litigation, Property, Wills and Estates.  \r\n', '2014-10-17 03:34:56', 0),
(116, 1160, 'Australian Transaction Reports and Analysis Centre (AUSTRAC)', 'upload/116/slogo.png', 'upload/116/llogo.png', 'F', '1300 021 037', 'help_desk@austrac.gov.au', '30', 'www.austrac.gov.au', 'AUSTRAC is an Australian Government organisation that tracks money laundering and financing of terrorism. We work to protect the integrity of Australia’s financial system and contribute to the administration of justice and protection of the Australian community.', '2014-10-17 03:34:56', 0),
(117, 1170, 'Ethos Corporation Melbourne', 'upload/117/slogo.png', 'upload/117/llogo.png', 'F', '03 9604 9000', 'melbourne@ethocorp.com.au ', '31', 'www.ethoscorporation.com.au', 'Ethos Corporation is deliberately, a compact human capital consultancy providing executive recruitment solutions to the Australian and Asia Pacific markets.\r\nFounded in 2004 and proudly Australian, Ethos Corporation is known as a knowledge based business where professional services practitioners combine subject matter expertise with deep access to candidate communities. \r\nOur founding principles are centred on two core aspects; what we do and the spirit in which we do it. We are dedicated to providing quality outcomes in a manner that is rare in the marketplace. \r\nOur team operate within chosen specialist disciplines. This allows for a level of penetration into the candidate market that is uncommon. We take pride in our approach being significantly more sophisticated and consultative than traditional executive recruitment agencies.\r\nThis deep level of specialisation combined with unmatched experience and a genuine flexible approach, positions us well to assist employers and employees with their unique recruitment needs.\r\n', '2014-10-17 03:34:56', 0),
(118, 1180, 'Yarra Trams - Keolis Downer', 'upload/118/slogo.png', 'upload/118/llogo.png', 'F', '03 9619 3200', '', '32', 'yarratrams.com.au', '', '2014-11-11 11:07:25', 0),
(119, 1190, 'Veda Advantage', 'upload/119/slogo.png', 'upload/119/llogo.png', 'F', '03 8629 1609', '', '34', 'www.veda.com.au', 'Veda is a data analytics business. As the leading provider of credit information and analysis in Australia and New Zealand, we act as the conduit between the data that we accumulate, and the insights that this data provides for our customers. The result of this process is empowerment. \r\n\r\nOur goal is to empower every one of our customers to make proactive, responsible and informed decisions, based on the insights we can provide.\r\nOur core product offering includes the provision of credit reports in relation to individuals and businesses. From our stable core credit bureau business, Veda has expanded to deliver a suite of credit and other analytical products targeted to specific industry segment needs. Veda’s data includes credit information on 20 million individuals and 5.7 million commercial entities in Australia and New Zealand.\r\n\r\nVeda has an international footprint in Singapore, Malaysia, Cambodia and Saudi Arabia.\r\n', '2014-10-17 03:34:56', 0),
(120, 1200, 'Heidrick & Struggles', 'upload/120/slogo.png', 'upload/120/llogo.png', 'F', '03 9012 3000', '', '35', 'www.heidrick.com', 'Heidrick & Struggles, is a premier provider of senior-level Executive Search, Culture Shaping and Leadership Consulting services. For more than 60 years, we have helped our clients build strong leadership teams through quality service, deep insights and our relationships with talented individuals worldwide. Today, Heidrick & Struggles’ leadership experts operate from principal business centers in North America, Latin America, Europe, Asia Pacific, Africa and the Middle East. For more information about Heidrick & Struggles, please visit www.heidrick.com', '2014-10-17 03:34:56', 0),
(121, 1210, 'Walker Anderson', 'upload/121/slogo.png', 'upload/121/llogo.png', 'F', '03 8640 5420', '', '35', 'www.walkerandersen.com', 'Established in 2010, we have brought together some of the industry’s most experienced, proactive and dedicated recruitment executives servicing the mid to senior management levels of Accounting across the Commerce & Industry, Professional Services, and Financial Services sectors on a permanent, contract, and interim basis.', '2014-10-17 03:34:56', 0),
(122, 1220, 'Baker Anderson', 'upload/122/slogo.png', 'upload/122/llogo.png', 'F', '03 8640 5410', '', '35', 'www.bakerandersen.com', 'Established in 2010, we have brought together some of the industry’s most experienced, proactive and dedicated recruitment executives servicing the mid to senior management levels of construction and resources industries on a permanent and contract basis.', '2014-10-17 03:34:56', 0),
(123, 1230, 'Stirling Anderson', 'upload/123/slogo.png', 'upload/123/llogo.png', 'F', '03 8640 5410', '', '35', 'www.stirlingandersen.com', 'Established in 2009, Stirling Andersen is the specialist Insurance brand of the Andersen Partnership. We specialize solely in the recruitment of Insurance professionals across General Insurance, Broking, Workers Compensation, Life Insurance and Superannuation. With Offices in Sydney, Melbourne, Brisbane and Perth we are a truly national specialist Insurance recruiter.', '2014-10-17 03:34:56', 0),
(124, 1240, 'Riverside', 'upload/124/slogo.png', 'upload/124/llogo.png', 'F', '03 8672 2000', 'eprendergast@riversidecompany.com', '35', 'www.riversidecompany.com.au', 'The Riverside Company is a global private equity firm focused on investing in growing enterprises valued at up to $250 million. The firm’s global portfolio includes more than 75 companies. Since its founding in 1988, Riverside has invested in more than 300 transactions.  We nurture companies with the goal of building them into more effective enterprises through time-tested management techniques, organic growth and add-on acquisitions.\r\n•	Strength: Over $4.6 billion in assets under management.\r\n•	Breadth: Over 345 completed acquisitions.\r\n•	Scope: Over 200 people on four continents worldwide.\r\n•	Experience: More than 25 years in business.\r\n', '2014-10-17 03:34:56', 0),
(125, 1250, 'Reliance Partners', 'upload/125/slogo.png', 'upload/125/llogo.png', 'F', '03 9604 2200', 'info@reliancepartners.com.au', '35', 'www.reliancepartners.com.au', 'At Reliance Partners, we are committed to creating a better insurance experience.  We’ve got you covered throughout your entire insurance journey.  From your initial meeting, to building tailored insurance solutions and managing any subsequent claims, we provide a completely seamless experience for you.  \r\nWith our dedicated claims team, you can rest assured that your insurance claims will be dealt with efficiently to get you back on track as quickly as possible.\r\nThe partnerships across our network have enabled us to buy big, giving us the ability to deliver value, variety and depth to meet your specific needs.  Our specialist teams across our business provide access to product and industry knowledge for your benefit.  This collaborative approach ensures that the very best resources are employed to develop your insurance solutions.\r\nYour Reliance Partner is local, informed, committed and available to help you whenever you need them.  They have access to produces, skills and resources to give you the best advice.\r\n', '2014-10-17 03:34:56', 0),
(126, 1260, 'Ambition', 'upload/126/slogo.png', 'upload/126/llogo.png', 'F', '03 8629 1000', 'info@ambition.com.au', '36', 'www.ambition.com.au', 'Ambition are experts in Finance and Technology. We have in-depth knowledge, recruitment expertise and ready access to the best talent.\r\nAt Ambition we are big enough to undertake large scale projects for our clients, yet retain the soul and personality of a smaller company.\r\nOur mantra is building better futures for our clients, candidates and wider community.\r\nWhether you are looking to hire or change roles we have a proven track record of delivering successful results. We recruit permanent and temporary staff in the following areas: Banking & Financial Services, Finance & Accounting and Technology.\r\n', '2014-10-17 03:34:56', 0),
(127, 1270, 'AccountAbility', 'upload/127/slogo.png', 'upload/127/llogo.png', 'F', '03 8629 1000', 'info@accountability.com.au', '36', 'www.accountability.com.au', 'AccountAbility are Australia’s leading accounting and business support recruitment specialists - and we’re proud of it. From humble beginnings as a team of two in 2004, we’ve grown into an established presence in Sydney, Parramatta, Melbourne and Brisbane. Last year we placed more than 450 candidates into permanent roles and over 800 into contract placements. \r\n\r\nWe recruit in the following functions: \r\n•	Accounts Payable, Accounts Receivable, Credit, Payroll, Assistant Accountant, Bookkeeping, Accounts Clerk. \r\n•	Executive Assistant, Personal Assistant, Receptionist, Office Manager, Customer Service, Data Entry, Administration Assistant. \r\n', '2014-10-17 03:34:56', 0),
(128, 1280, 'Blackstone Waterhouse Zouki Lawyers', 'upload/128/slogo.png', 'upload/128/llogo.png', 'F', '03 9988 8980', 'info@bwz.com.au', '36', 'www.bwz.com.au ', 'Blackstone Waterhouse Zouki Lawyers provides expert legal services to individuals and corporations in a range of practice areas. We cover all areas of commercial and criminal law, as well as other general legal services in areas such as property and family law, business sales and purchases, litigation, conveyancing, wills, migration law, medical negligence and Coronial matters.', '2014-10-17 03:34:56', 0),
(129, 1290, 'Munich RE', 'upload/129/slogo.png', 'upload/129/llogo.png', 'F', '', '', '36', '', 'Munich Holdings of Australasia Pty Limited\nMunich Reinsurance Company of Australasia Limited\nMunich Reinsurance Company – Australian Branch\nGreat Lakes Australia (Branch)', '2014-11-11 11:13:50', 0),
(130, 1300, 'FM Global', 'upload/130/slogo.png', 'upload/130/llogo.png', 'F', '03 9609 1300', 'enquiries@fmglobal.com.au', '37', 'www.fmglobal.com.au', 'Factory Mutual Insurance Company\nFM Insurance Company Ltd.\nFM Global\nAffiliated FM\n\nFM Global provides comprehensive global commercial and industrial property insurance, engineering-driven underwriting and risk management solutions, ground breaking property loss prevention research and prompt, professional claims handling.', '2014-11-11 11:14:42', 0),
(131, 1310, 'Affiliated FM', 'upload/131/slogo.png', 'upload/131/llogo.png', 'F', '03 9609 1300', 'enquiries@fmglobal.com.au', '37', 'www.affiliatedfm.com.au', 'Factory Mutual Insurance Company\nFM Insurance Company Ltd.\nFM Global\nAffiliated FM\n\nAffiliated FM specializes in commercial property insurance for the middle-market segment of business and industry. Affiliated FM provides tailored underwriting expertise and property loss control engineering through a select international network of producers and broker partners.', '2014-11-11 11:14:59', 0),
(132, 1320, 'Barristers Chambers', 'upload/132/slogo.png', 'upload/132/llogo.png', 'F', '03 9225 8888', 'bcl@vicbar.com.au', '38', 'www.bcl.net.au', 'Barristers’ Chambers Limited (BCL) provides accommodation and other facilities and services to Barristers and to The Victorian Bar. \n\nBCL owns and leases buildings conveniently located near the principal court complexes in Melbourne and presently maintains for rent 70 floors of commercial space in the court precinct for this purpose.\n\nBCL also offer IT&T services to Barristers.', '2014-11-11 11:16:47', 0),
(133, 1330, 'Robert Half', 'upload/133/slogo.png', 'upload/133/llogo.png', 'F', '03 9691 3631', 'melbourne@roberthalf.com.au', '39', 'www.roberthalf.com.au', 'Founded in 1948, Robert Half (NYSE symbol: RHI) pioneered specialised recruitment services and today is the world’s leader in placing accounting, finance, banking and technology professionals on a temporary and permanent basis.', '2014-10-17 03:34:56', 0),
(134, 1340, 'John B Prescott AC', '', '', 'F', '03 9642 2518', 'jbp@jbprescott.com', '39', '', 'Company Director and Business Advisory Services', '2014-11-11 12:23:55', 0),
(135, 1350, 'Aurizon Holdings', 'upload/135/slogo.png', 'upload/135/llogo.png', 'F', '03 9642 2518', 'jbp@jbprescott.com', '39', 'www.aurizon.com.au', 'Aurizon is Australia’s largest rail freight operator with almost 150 years of experience. Each day the Company moves on average more than 700,000 tonnes of coal, iron ore and other minerals as well as agricultural and general freight across the nation.\r\n\r\nAurizon operates a coal network made up of approximately 2,670 kilometres of heavy haul rail infrastructure in Central Queensland. The Company also provides a range of specialist services in rail design, engineering, construction, management and maintenance, and offers large-scale supply chain solutions to a diverse range of customers Australia-wide. \r\n\r\nAurizon has played a critical role in the economic development and growth of the minerals-rich state of Queensland, providing the transport backbone for one of the world’s largest coal supply chains. Over recent years Aurizon has extended its business focus beyond its Queensland heritage and applied its expertise and capabilities to coal and iron ore opportunities in New South Wales and Western Australia, as well as intermodal freight across the nation. \r\n\r\nAurizon’s business comprises four major product lines – Coal, Iron Ore, Intermodal & Bulk and Network. The Company’s performance and future growth is linked to the key demand drivers of the Australian resources sector and ongoing strength of the Australian economy. Aurizon is well placed to benefit from the continued long-term growth in demand for coal and iron ore, particularly from fast growing Asian economies such as China and India. \r\n', '2014-10-17 03:34:56', 0),
(136, 1360, 'Balmain', 'upload/136/slogo.png', 'upload/136/llogo.png', 'F', '03 9617 5333', 'info@balmain.com.au', '39', 'www.balmain.com.au', 'Balmain is a broad based financial services organisation, with activities spanning commercial mortgage finance (both arranging and lending) and investment funds management. Our skilled people and unique ability to access wholesale institutional funds, bank balance sheets, retail funds management and private markets both locally and overseas has enabled Balmain to provide a funding experience which cannot be matched.', '2014-10-17 03:34:56', 0),
(137, 1370, 'Servcorp', 'upload/137/slogo.png', 'upload/137/llogo.png', 'F', '03 9607 8200', 'offices@servcorp.com.au', '40', 'www.servcorp.com.au', 'Servcorp is the world leader in high-quality Serviced and Virtual Office products and IT services. Our simple proposition is that our clients will be more successful in a Servcorp facility. They will make more sales because of the Unique Selling Propositions that we offer.', '2014-10-17 03:34:56', 0),
(138, 1380, 'Ascentor', 'upload/138/slogo.png', 'upload/138/llogo.png', 'F', '1300 674 700', 'enquiries@ascentor.com.au', '40', 'www.ascentor.com.au', 'Ascentor believes that a company can achieve excellent workers compensation results when it manages risk ‘in-house’. It’s more about how ‘people’ are managed than how insurance claims are managed. Ascentor can provide the tools, training and coaching to support executives and foster line-manager engagement in the day-to-day business of managing people and containing risk.', '2014-10-17 03:34:56', 0),
(139, 1390, 'Carrington King', 'upload/139/slogo.png', 'upload/139/llogo.png', 'F', '03 9607 8555', 'email@carringtonking.com.au', '40', 'www.carringtonking.com.au', 'An Australian firm offering a highly personalised consulting service and excellence in the delivery of executive recruitment solutions, our sophisticated sourcing strategies identify and attract candidates across the total market.', '2014-10-17 03:34:56', 0),
(140, 1400, 'Clyde & Co Australia', 'upload/140/slogo.png', 'upload/140/llogo.png', 'F', '03 8600 7200', '', '40', 'www.clydeco.com', 'Clyde & Co is a global law firm with a pioneering heritage and a resolute focus on its core sectors of aviation, energy, infrastructure, insurance, marine, and trade.', '2014-10-17 03:34:56', 0),
(141, 1410, 'CBL Business Lawyers', 'upload/141/slogo.png', 'upload/141/llogo.png', 'F', '03 9098 8668', 'mail@cblbusinesslawyers.com.au', '40', 'www.cblbusinesslawyers.com.au', 'CBL Business Lawyers is a progressive legal practice which embraces technology to provide innovative and practical legal solutions to clients in a manner that the modern business world justifiably expects that legal services ought to be provided. \r\nCBL Business Lawyers acts for large, medium and small company and business enterprises in all professions and industries. We act in many fields of law including commercial debt recovery, commercial litigation and disputes, alternative dispute resolution, commercial advice and business solutions, contracts and agreements and business and commercial transactions. We also promote professional affiliations between our firm and accountants, insolvency practitioners and other lawyers.\r\nCBL Business Lawyers is a modern law firm at the forefront of change in the legal industry.  We are not a traditional law firm.\r\n', '2014-10-17 03:34:56', 0),
(142, 1420, 'DDS Australia ', 'upload/142/slogo.png', 'upload/142/llogo.png', 'F', '03 9607 8286', 'info@ddsaustralia.com.au', '40', 'www.ddsaustralia.com.au', 'DDS are specialists in providing Project Management, Project Controls and Engineering solutions across the Australian and Asia Pacific region.', '2014-10-17 03:34:56', 0),
(143, 1430, 'empire careers', 'upload/143/slogo.png', 'upload/143/llogo.png', 'F', '03 9098 8750', 'melbourne@empirecareers.com.au', '40', 'www.empirecareers.com.au', 'empire careers is a recruitment company with offices in Brisbane, Sydney, Melbourne and Perth. We specialise in Legal Professional, Corporate Support and Medical Administration recruitment.  Our consultants are dedicated, understand the business world and employment industry inside and out, have great connections, and know how to get you where you want to be. We’re not here to simply find you a job. We’re here to help you make the best professional move you’ll ever make and enjoy the journey with you along the way.', '2014-10-17 03:34:56', 0),
(144, 1440, 'Hicksons Lawyers', 'upload/144/slogo.png', 'upload/144/llogo.png', 'F', '03 9607 8212', 'hicksons.reception@hicksons.com.au', '40', 'www.hicksons.com.au', 'With beginning in 1897, the firm has grown to become a highly respected medium-size law firm serving our long standing private and public sector clients. We are totally committed and always direct in everything we do. Today the firm operates across Australia with offices in Sydney, Newcastle, Canberra, Melbourne and Brisbane.', '2014-10-17 03:34:56', 0),
(145, 1450, 'Hopkins Lawyers', 'upload/145/slogo.png', 'upload/145/llogo.png', 'F', '03 9607 8279', 'mailbox@hopkinslawyers.com.au', '40', 'www.hopkinslawyers.com.au', 'Helping businesses recover money and resolve disputes quickly using contemporary methods of appropriate dispute resolution, litigation, bankruptcy, corporate insolvency and debt collection.', '2014-10-17 03:34:56', 0),
(146, 1460, 'Komesaroff Legal', 'upload/146/slogo.png', 'upload/146/llogo.png', 'F', '03 9229 3888', 'akomesaroff@komlegal.com', '40', 'www.komlegal.com', '', '2014-10-17 03:34:56', 0),
(147, 1470, 'The Videoconferencing Centre', '', '', 'F', '03 9607 8299', 'info@thevccentre.com', '40', 'www.thevccentre.com.au', 'Videoconferencing is a powerful, proven, strategic tool that lets you operate your business more efficiently, productively and profitably. The Videoconferencing Centre can show you how to meet your specific business needs effectively and affordably.', '2014-11-11 12:25:49', 0),
(148, 1480, 'NIIT Technologies', 'upload/148/slogo.png', 'upload/148/llogo.png', 'F', '03 9607 8264', 'marketing@niit-tech.com', '40', 'www.niit-tech.com', 'NIIT Technologies is a leading IT solutions organization, servicing customers in the Americas, Europe, Asia and Australia. It offers services in Application Development and Maintenance, Enterprise Solutions including Managed Services and Business Process Outsourcing to enterprise in the Financial Services, Travel & Transportation, Manufacturing/Distribution, and Government sectors.  ', '2014-10-17 03:34:56', 0),
(149, 1490, 'Watson Goode International', '', '', 'F', '03 9607 8493', 'enquiries@wgi.com.au', '40', 'www.wgi.com.au', 'Watson Goode is a successful and growing management services consultancy that offers search and selection recruitment, coaching, and board advisory services.', '2014-11-11 12:26:14', 0),
(150, 1500, 'Advice Services Australia', 'upload/150/slogo.png', 'upload/150/llogo.png', 'F', '1300 327 689', 'info@adviceservices.com.au', '40', 'www.adviceservices.com.au', 'Our expert financial planners will help you manage money, create wealth, manage investments, select insurance, build super, plan your retirement and more. Advice Services Australia can help put you on the path to achieving your dreams.', '2014-10-17 03:34:56', 0),
(151, 1510, 'Archbold Legal ', 'upload/151/slogo.png', 'upload/151/llogo.png', 'F', '03 9098 8653', '', '40', 'www.archboldlegal.com.au', 'We are an experienced law firm that is highly motivated and fearless in the pursuit of justice for our clients.\r\nSolicitor Director Benjamin Archbold has spent 20 years in and around the Australian Legal System, first as a serving Detective and currently as a qualified Solicitor and Barrister.\r\nOur firm provides affordable legal advice and representation in most areas of law but has vast experience and knowledge in the criminal jurisdiction.\r\nWe regularly and successfully represent people in State and Federal Police matters and more complex NSW and Australian Crime Commission cases.\r\nOur Solicitors are expertly trained and possess a dogged determination to obtain the best result possible for you, the client.\r\n', '2014-10-17 03:34:56', 0),
(152, 1520, 'BIR Solutions', 'upload/152/slogo.png', 'upload/152/llogo.png', 'F', '1300 783 309', 'info@bir.net.au ', '40', 'www.bir.net.au', 'If you want to solve your problems sustainably and you don’t think you and your team have the time, experience or expertise to do all of this yourself, then we might be able to help you.\r\nThe team at BIR Solutions love to help you identify and pick your low hanging fruit, avoid business insanity and encourage your chappies to be happy chappies!', '2014-11-07 03:34:56', 0),
(153, 1530, 'CE Family Lawyers', 'upload/153/slogo.png', 'upload/153/llogo.png', 'F', '03 9607 8249', 'mail@cefamilylawyers.com.au', '40', 'www.cefamilylawyers.com.au', 'We are a team of family lawyers committed to achieving fair and cost effective solutions to issues arising from separation and divorce, focussing on achieving our client’s goals.', '2014-10-17 03:34:56', 0),
(154, 1540, 'Core Reality', 'upload/154/slogo.png', 'upload/154/llogo.png', 'F', '03 9067 8444 / 0412 347 838', 'info@corereality.com.au', '40', 'www.corereality.com.au', 'Core Reality assists corporations and business leaders address both broad commercial legal problems and business challenges/strategies relevant to how companies are directed and managed.  The goal is to enable companies to attain their strategic desired outcomes, monitor risks and improve optimal performance.  \r\nOur mission is to work with companies on issues of significance bringing a distinctive capability beyond the client’s own skills and capacity to generate or re-invigorate enduring and substantial improvement.\r\n', '2014-10-17 03:34:56', 0),
(155, 1550, 'Cullinan Consulting', 'upload/155/slogo.png', 'upload/155/llogo.png', 'F', '03 9098 8780', 'info@cullinangroup.com', '40', 'www.cullinangroup.com', 'Cullinan deliver self-service money transfer for major retailers', '2014-10-17 03:34:56', 0),
(156, 1560, 'Curran & Associates', 'upload/156/slogo.png', 'upload/156/llogo.png', 'F', '03 9607 8475', 'jk@curranrecruit.com.au', '40', 'www.curranrecruit.com.au ', 'We are a specialised Executive Recruitment Agency who recruit across Australia and South-East Asia. We have offices in Sydney, Melbourne and Manila. The company was started in 1998 by the CEO Geoff Curran. At Curran + Associates we strongly believe that specialisation provides greater reliability and accuracy when recommending candidates, as well as enhancing the quality and speed of service provided to clients and job-seekers.Our mission is to be recognised as a national and international recruitment leader in our areas of specialisation.To be respected for our skill in delivering solutions so that the needs of both clients and candidates are equally satisfied.', '2014-10-17 03:34:56', 0),
(157, 1570, 'de JAGER Executive Search', 'upload/157/slogo.png', 'upload/157/llogo.png', 'F', '03 9098 8613 /  0408 033 448', 'ross@dejager.com.au', '40', 'dejager.com.au ', 'de JAGER Executive Search was founded in 1990 and is now one of Asia Pacific’s premier retained executive search firms.Headquartered in Sydney with an office in Melbourne, the firm has a distinguished track record of successfully completing global and regional search mandates at the C-suite level.  This has been achieved by collaborating in proactive and principled partnerships with clients who comprise a register of high profile, ethical and prestigious Australian and International industry leaders.   de JAGER’s primary spheres of specialty include the automotive, life sciences, industrial, not for profit, board, technology and FMCG sectors.Since 2002, de JAGER Executive Search has been the Australian affiliate of IIC Partners, the 8th largest executive search group in the world - with offices in over 60 countries.', '2014-10-17 03:34:56', 0),
(158, 1580, 'Dominium Capital Group', 'upload/158/slogo.png', 'upload/158/llogo.png', 'F', '03 9607 8294', 'enquiries@dominiumcapital.com.au', '40', 'www.dominiumcapital.com.au', 'We are a diversified Private Wealth Management firm, which strives to provide an adaptable, holistic service to assist our clients in optimising their total wealth and maximising every opportunity. If you want to engage Advisers, Advocates and Consultants who can quickly understand your needs and offer tailored solutions to those needs, ask us about what we do and how we do it - we know you’ll appreciate the difference.', '2014-10-17 03:34:56', 0),
(176, 1770, 'M&T Resources', 'upload/176/slogo.png', 'upload/176/llogo.png', 'F', '03 9674 3388', 'melbourne@mtr.com.au', '41', 'www.mtr.com.au', 'Multi-award-winning business and IT recruitment company with a history of helping people achieve greater success. Consistently voted Australia’s Favourite Medium IT Recruiter. Actively champions workplace diversity and equal opportunity through the DIVERSITY initiative. A division of SMS Management & Technology Limited [ASX: SMX] with offices across major Australian cities. ', '2014-10-21 14:52:38', 0),
(177, 1780, 'JLL', 'upload/177/slogo.png', 'upload/177/llogo.png', 'F', '03 8636 7900', 'concierge@520demost.com', '42', 'www.jll.com.au', 'JLL is a professional services and investment management firm specialising in real estate. We offer integrated services delivered by expert teams worldwide to clients seeking increased value by owning, occupying, developing or investing in real estate.', '2014-10-21 14:52:38', 0),
(159, 1590, 'Merifield Financial Services', 'upload/159/slogo.png', 'upload/159/llogo.png', 'F', '03 9600 3355', 'enquiries@dominiumcapital.com.au / office@merifield.com.au', '40', 'www.dominiumcapital.com.au', 'Fee-for-service Financial Advice. If we don’t buy it, you don’t buy it. We all sell together.', '2014-10-17 03:34:56', 0),
(169, 1690, 'McBain Lawyers', 'upload/169/slogo.png', 'upload/169/llogo.png', 'F', '03 9606 0160', 'admin@mcbainlawyers.com.au', '40', 'www.mcbainlawyers.com.au', 'McBain Lawyers is a boutique dynamic and progressive Melbourne based firm offering sound advice, effective strategies and the best possible outcomes in  Family law We offer premium legal services at cost-effective rates. Here at McBain Lawyers we pride ourselves on excellence in client service. With a track record of success, Rob McBain and his support staff take the time needed to fully understand our clients’ legal position and to provide both clear, understandable advice and strong representation for all legal matters.', '2014-10-21 14:52:38', 0),
(170, 1700, 'Nexus', '', '', 'F', '1300 782 131', 'chrisnexuspartners.com.au', '40', 'www.nexuspartners.com.au', 'Nexus Partners provides you with access to simple and effective referral processes that support your core business activities without the need for extra resourcing and administrative constraints. We offer a fresh approach with equitable commission plans and we believe you’ll benefit from partnering with an industry innovator who will work closely with you to provide a broader product offering for your clients', '2014-11-11 12:24:44', 0),
(171, 1710, 'SPL Security Group', 'upload/171/slogo.png', 'upload/171/llogo.png', 'F', '1800 775 253 (24 hours)', 'CBD@Splsecuritygroup.com.au', '40', 'www.splsecuritygroup.com.au', 'As one of Melbourne’s oldest and most established security firms, the SPL Security Group has been providing security services throughout metropolitan and Regional Victoria for over 20 years.  \r\nSPL Security Group provides a range of tailored security solutions with the most up to date technology to protect your business, home and assets. All security guards and management are qualified, trained and licensed with ongoing coaching to continually adapt to new legislation within the security industry and modern business environment. \r\nSPL Security Group’s performance history, management expertise, comprehensive business systems and infrastructure demonstrate a high capacity to deliver a range of exceptional services. With the integrity and commitment that is required to provide superior services which meet our clients’ needs. With 24/7 telephone support and management services and quality trained professional guards to reflect the growth of the security industry.\r\nSPL Security Group currently provide services to Residential, Government and Industrial sectors and able to provide security guards services such as, but not limited to:\r\nGeneral Security Guard duties, Mobile (Foot & Vehicle) Patrols, Event Security, Emergency Response, Nightclubs, Pubs, Bars, Schools, Hospitals, Places of worship, Construction/Building sites, Hotels, TAB’s, Banking and Finance, Gate house/Concierge, Commercial & Retail.\r\nFor further information please the nearest office:  Melbourne CBD (Located here), Dandenong or Derrimut.\r\n', '2014-10-21 14:52:38', 0),
(172, 1720, 'Wentworth Lawyers', '', '', 'F', '03 9607 8380', 'admin@wentworthlawyers.com.au', '40', 'www.wentworthlawyers.com.au', 'Wentworth Lawyers Pty Ltd are a boutique commercial law advice practice with a particular emphasis on not-for-profit sporting community clubs. We also provide commercial advice to a range of SME’s and publicly listed companies but with a particular emphasis on providing taxation advice to NFP’s. We act for clubs ranging from professional football leagues to local community clubs across eastern Australia. Additionally we represent and advise club peak bodies on taxation matters affecting NFP’s.', '2014-11-11 12:26:50', 0),
(173, 1730, 'Xantias', 'upload/173/slogo.png', 'upload/173/llogo.png', 'F', '03 8626 0888', 'info@xantias.com.au', '40', 'www.xantias.com.au', 'Xantias is an independently owned financial advisory firm committed to providing the highest-quality financial solutions for discerning clients. \r\nXantias is not aligned with any single financial institution. Therefore we are not restricted in the range of possible financial solutions we offer you. \r\nMany financial advisory firms provide financial advice centred around a given number of widely available listed investments. Xantias, however, provides you with access to a broader range of opportunities, including innovative offerings tailored specifically for our clients. With greater choice comes a greater capacity to achieve personal goals and lifestyle aspirations. ', '2014-10-21 14:52:38', 0),
(174, 1740, 'Legal eagles', 'upload/174/slogo.png', 'upload/174/llogo.png', 'F', '03 9098 8750', 'melbourne@legal-eagles.net.au', '40', 'www.legal-eagles.net.au', 'legal eagles is a recruitment company with offices in Melbourne, Sydney, Brisbane and Perth specialising in Legal Support recruitment. Our consultants are dedicated, understand the legal profession inside and out, have great connections and know how to get you where you want to be. We’re not here to simply find you a job. We’re here to help you make the best professional move you’ll ever make and enjoy the journey with you along the way.', '2014-10-21 14:52:38', 0),
(175, 1760, 'SMS Management & Technology (Reception Floor 41)', 'upload/175/slogo.png', 'upload/175/llogo.png', 'F', '1300 842 767', 'reception.mel@smsmt.com', '41 & 26', 'www.smsmt.com', 'SMS Management & Technology is a leading Asia-Pacific consulting, technology and managed services company.\r\nWe help our clients improve their business performance through the implementation of strategy and the delivery of business and technology projects. Our industry expertise spans the financial services, ICT, government, defence, health, utilities, mining, gaming and infrastructure sectors. We employ in excess of 1,700 professionals in offices throughout Australia, Hong Kong, Vietnam and Singapore\r\n', '2014-11-11 11:06:06', 0),
(160, 1600, 'Epiphany Advisory Group', 'upload/160/slogo.png', 'upload/160/llogo.png', 'F', '03 9098 8665', 'mark@epiphanyadvisorygroup.com', '40', 'www.epiphanyadvisorygroup.com', 'EAG is a business and technology consultancy based in Melbourne, working with our clients across Australia and Asia Pacific. Over the last 4 decades our principals have been working with and for major regional and global leaders resulting in a range of long-standing relationships, focused on innovation and enablement — especially when it comes to technology.\r\nEAG collaborates and partners with industry leading subject matter experts to ensure that our clients receive the very best advice and assistance available.  Equally, EAG has developed our Inspired™ Methodology to ensure that we work in partnership with our client’s team to enable the greatest level of knowledge and skill transfer possible.\r\n', '2014-10-17 03:34:56', 0),
(161, 1610, 'Felton Farquar & Co', '', '', 'F', '03 9607 8410', '', '40', '', '', '2014-11-11 11:49:19', 0),
(162, 1620, 'First Recruitment International', 'upload/162/slogo.png', 'upload/162/llogo.png', 'F', '03 9607 8417', 'apply@firstint.com', '40', 'www.firstint.com', 'As leaders in the executive search and recruitment industry, First Recruitment International solves business problems for our clients every day, anywhere in the world.', '2014-10-21 14:52:38', 0),
(163, 1630, 'Garde Wilson Lawyers', '', '', 'F', '03 9600 0202', 'law@gwlawyers.com.au', '40', 'www.gardewilson.com', 'Be represented by one of Australia’s leading Law Firms. Our barristers have decades of experience representing people just like you.', '2014-11-11 12:22:47', 0);
INSERT INTO `bldgdir_company` (`company_id`, `sort_number`, `name`, `small_logo_path`, `large_logo_path`, `lift_bank`, `phone`, `email`, `levels`, `website`, `information`, `update_time`, `disabled`) VALUES
(164, 1640, 'GDA Group', 'upload/164/slogo.png', 'upload/164/llogo.png', 'F', '03 9229 3875', 'admin@gdas.com.au', '40', 'www.gdagroup.com.au', 'The GDA Group is Australian, independently owned and non- aligned and provides financial services to clients in every state in Australia and a number of overseas countries. GDA has provided financial services to our clients for over 20 years and our qualified advisers have over 100 years combined experience.', '2014-10-21 14:52:38', 0),
(165, 1650, 'Greenmonts', 'upload/165/slogo.png', 'upload/165/llogo.png', 'F', '03 9229 3826', 'info@greenmonts.com.au', '40', 'www.greenmonts.com.au', 'Greenmonts operates as a network of firms offering legal and consulting services in the corporate and government sectors. We work closely with our clients, helping them to solve problems, mitigate risks and grasp opportunities', '2014-10-21 14:52:38', 0),
(166, 1660, 'Harmers  Workplace Lawyers', '', '', 'F', '03 9612 2300', '', '40', 'www.harmers.com.au', 'Harmers Workplace Lawyers (formerly Michael Harmer & Associates) was formed in 1996 and is one of Australia’s largest employment and industrial law practices with offices in Sydney, Melbourne and Brisbane. The firm has enjoyed its rapid growth through its ability to provide quality, effective, practical and timely legal services. By minimising overhead costs, we have fixed a highly competitive fee structure without compromising the quality of the service we provide. Our diverse client base includes many of Australia’s most prominent companies (both listed and private), employer associations, media personalities and senior executives. The firm also has a significant pro bono scheme, consistent with its charter to ensure fairness in the workplace', '2014-11-11 12:23:29', 0),
(167, 1670, 'Integra Technical Services', 'upload/167/slogo.png', 'upload/167/llogo.png', 'F', '03 9229 3820', 'stephen.thorpe@integratechnical.com', '40', 'www.integraaustralia.com.au', 'Integra Technical Services is a preeminent, privately owned chartered loss-adjusting business, specialising in managing a professional portfolio of large and complex losses.', '2014-10-21 14:52:38', 0),
(168, 1680, 'International Business Mentors', 'upload/168/slogo.png', 'upload/168/llogo.png', 'F', '03 96070 8270', 'info@InternationalBusinessMentors.com', '40', 'www.internationalbusinessmentors.com', 'We match & provide Business Mentors for:\r\n\r\n• •     Business Owners\r\n• •     CEOs\r\n• •     Directors and\r\n• •      Senior Executives \r\n\r\nTo develop & improve their individual growth, performance & business success.\r\n', '2014-10-21 14:52:38', 0),
(178, 1750, 'Gain Wealth Management', '', '', 'F', '03 9607 8440', 'info@gainwealth.com.au ', '40', 'www.gainwealth.com.au', 'Gain Wealth is a boutique wealth advisory firm focused on customer service, a wide product portfolio, and a fair fee structure in the Australian financial services industry. Gain Wealth has grown to be one of the leading boutique practices in Australia.', '2014-11-11 12:22:16', 0);

-- --------------------------------------------------------

--
-- Table structure for table `bldgdir_company_sub`
--

CREATE TABLE IF NOT EXISTS `bldgdir_company_sub` (
`cosub_id` int(4) unsigned NOT NULL,
  `company_id` int(4) unsigned NOT NULL,
  `sort_number` int(4) unsigned NOT NULL,
  `logo_path` varchar(100) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `levels` varchar(20) DEFAULT NULL,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=28 ;

--
-- Dumping data for table `bldgdir_company_sub`
--

INSERT INTO `bldgdir_company_sub` (`cosub_id`, `company_id`, `sort_number`, `logo_path`, `name`, `levels`, `update_time`) VALUES
(1, 132, 1, 'upload/132/sub_logo.png', 'Greg Ahern, Barrister', '38', '2014-10-29 02:46:38'),
(2, 132, 2, 'upload/132/sub_logo.png', 'Christopher Archibald, Barrister', '38', '2014-10-29 02:46:38'),
(3, 132, 3, 'upload/132/sub_logo.png', 'David Batt QC, Barrister', '38', '2014-10-29 02:46:38'),
(4, 132, 4, 'upload/132/sub_logo.png', 'Kate Beattie, Barrister', '38', '2014-10-29 02:46:38'),
(5, 132, 5, 'upload/132/sub_logo.png', 'Michael Borsky, Barrister', '38', '2014-10-29 02:46:38'),
(6, 132, 6, 'upload/132/sub_logo.png', 'Sharon Burchell, Barrister', '38', '2014-10-29 02:46:38'),
(7, 132, 7, 'upload/132/sub_logo.png', 'Catherine Button, Barrister', '38', '2014-10-29 02:46:38'),
(8, 132, 8, 'upload/132/sub_logo.png', 'Andrew Cameron, Barrister', '38', '2014-10-29 02:46:38'),
(9, 132, 9, 'upload/132/sub_logo.png', 'Tom Clarke, Barrister', '38', '2014-10-29 02:46:38'),
(10, 132, 10, 'upload/132/sub_logo.png', 'Georgina Costello, Barrister', '38', '2014-10-29 02:46:38'),
(11, 132, 11, 'upload/132/sub_logo.png', 'Albert Dinelli, Barrister', '38', '2014-10-29 02:46:38'),
(12, 132, 12, 'upload/132/sub_logo.png', 'Kathleen Foley, Barrister', '38', '2014-10-29 02:46:38'),
(13, 132, 13, 'upload/132/sub_logo.png', 'Perry Herzfeld, Barrister', '38', '2014-10-29 02:46:38'),
(14, 132, 14, 'upload/132/sub_logo.png', 'Laura Keily, Barrister', '38', '2014-10-29 02:46:38'),
(15, 132, 15, 'upload/132/sub_logo.png', 'Lucy Kirwan, Barrister', '38', '2014-10-29 02:46:38'),
(16, 132, 16, 'upload/132/sub_logo.png', 'Christina Klemis, Barrister', '38', '2014-10-29 02:46:38'),
(17, 132, 17, 'upload/132/sub_logo.png', 'Jonathon Moore QC, Barrister', '38', '2014-10-29 02:46:38'),
(18, 132, 18, 'upload/132/sub_logo.png', 'David Morgan, Barrister', '38', '2014-10-29 02:46:38'),
(19, 132, 19, 'upload/132/sub_logo.png', 'Mark Moshinsky QC, Barrister', '38', '2014-10-29 02:46:38'),
(20, 132, 20, 'upload/132/sub_logo.png', 'Patrick Noonan, Barrister', '38', '2014-10-29 02:46:38'),
(21, 132, 21, 'upload/132/sub_logo.png', 'Simon Pitt, Barrister', '38', '2014-10-29 02:46:38'),
(22, 132, 22, 'upload/132/sub_logo.png', 'Jonathon Redwood, Barrister', '38', '2014-10-29 02:46:38'),
(23, 132, 23, 'upload/132/sub_logo.png', 'Suresh Senathirajah, Barrister', '38', '2014-10-29 02:46:38'),
(24, 132, 24, 'upload/132/sub_logo.png', 'Tamieka Spencer Bruce, Barrister', '38', '2014-10-29 02:46:38'),
(25, 132, 25, 'upload/132/sub_logo.png', 'Caryn van Proctor, Barrister', '38', '2014-10-29 02:46:38'),
(26, 132, 26, 'upload/132/sub_logo.png', 'Christopher Young, Barrister', '38', '2014-10-29 02:46:38'),
(27, 132, 27, 'upload/132/sub_logo.png', 'Neil Young QC, Barrister', '38', '2014-10-29 02:46:38');

-- --------------------------------------------------------

--
-- Table structure for table `bldgdir_management`
--

CREATE TABLE IF NOT EXISTS `bldgdir_management` (
`management_id` int(4) unsigned NOT NULL,
  `name` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `location` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `phone` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `website` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `logo_path` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `about_us` text COLLATE utf8_unicode_ci NOT NULL,
  `contact_us` text COLLATE utf8_unicode_ci NOT NULL,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `admin_username` varchar(30) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'admin',
  `admin_password` varchar(30) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'password'
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=2 ;

--
-- Dumping data for table `bldgdir_management`
--

INSERT INTO `bldgdir_management` (`management_id`, `name`, `location`, `phone`, `email`, `website`, `logo_path`, `about_us`, `contact_us`, `update_time`, `admin_username`, `admin_password`) VALUES
(1, 'JLL (Jones LaSalle Incorporated)', 'Concierge Desk', '03 8636 7900', 'concierge@520demost.com', 'www.jll.com.au', 'upload/logo/jll.png', 'JLL is a professional services and investment management firm specialising in real estate. We offer integrated services delivered by expert teams worldwide to clients seeking increased value by owning, occupying, developing or investing in real estate.', '', '2014-10-16 14:08:35', 'Username', 'Password');

-- --------------------------------------------------------

--
-- Table structure for table `bldgdir_setting`
--

CREATE TABLE IF NOT EXISTS `bldgdir_setting` (
  `setting_id` int(4) unsigned NOT NULL,
  `name` varchar(30) NOT NULL,
  `value` varchar(255) DEFAULT NULL,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dumping data for table `bldgdir_setting`
--

INSERT INTO `bldgdir_setting` (`setting_id`, `name`, `value`, `update_time`) VALUES
(100, 'position_number', 'M', '2014-11-04 23:45:29');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `bldgdir_company`
--
ALTER TABLE `bldgdir_company`
 ADD PRIMARY KEY (`company_id`), ADD KEY `levels` (`levels`), ADD KEY `name` (`name`), ADD KEY `sort_number` (`sort_number`);

--
-- Indexes for table `bldgdir_company_sub`
--
ALTER TABLE `bldgdir_company_sub`
 ADD PRIMARY KEY (`cosub_id`);

--
-- Indexes for table `bldgdir_management`
--
ALTER TABLE `bldgdir_management`
 ADD PRIMARY KEY (`management_id`);

--
-- Indexes for table `bldgdir_setting`
--
ALTER TABLE `bldgdir_setting`
 ADD PRIMARY KEY (`setting_id`), ADD UNIQUE KEY `name` (`name`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `bldgdir_company`
--
ALTER TABLE `bldgdir_company`
MODIFY `company_id` int(4) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=179;
--
-- AUTO_INCREMENT for table `bldgdir_company_sub`
--
ALTER TABLE `bldgdir_company_sub`
MODIFY `cosub_id` int(4) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=28;
--
-- AUTO_INCREMENT for table `bldgdir_management`
--
ALTER TABLE `bldgdir_management`
MODIFY `management_id` int(4) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
